In [9]:
import pandas as pd
student_data={
    "Roll_No":[101,102,103,104],
    "Name":["Anusha","Babitha","Charitha","Deepika"],
    "Department":["IT","IT","CSE","ECE"],
    "Percentage":[89,92,88,85]
}
df=pd.DataFrame(student_data)
df.to_csv("student_output.txt",sep="\t",index=False)
print("Data successfully written to student_output.txt")

Data successfully written to student_output.txt

In [11]:
import pandas as pd
url="https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df=pd.read_csv(url)
df.to_csv("iris_output.csv",index=False)
print("The dataset has been successfully written to iris_output.csv")

The dataset has been successfully written to iris_output.csv

In [12]:
import pandas as pd
data={
    'S.No' :[1,2,3,4,5,6],
    'Name':['Ravi','Sai','Raju','Siva','Nani','Teja'],
    'Subject' :['Telugu','Hindi','English','Math','Science','Social'],
    'Marks' :[98,87,84,97,79,89]
}
dfw=pd.DataFrame(data)
dfw

   S.No  Name  Subject  Marks
0     1  Ravi   Telugu     98
1     2   Sai    Hindi     87
2     3  Raju  English     84
3     4  Siva     Math     97
4     5  Nani  Science     79
5     6  Teja   Social     89

In [13]:
#Data Frames

import pandas as pd
data ={
    'Name' :['sai','ravi','raju'],
    'Marks' :[90,89,99]
}
df=pd.DataFrame(data)
df

   Name  Marks
0   sai     90
1  ravi     89
2  raju     99

In [14]:
#Series

import pandas as pd
marks =pd.Series([98,99,95])
print(marks)

0    98
1    99
2    95
dtype: int64

In [15]:
import pandas as pd
url="https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df=pd.read_csv(url)
df.to_csv("iris_output.csv",index=False)
print("The dataset has been successfully written to iris_output.csv")

The dataset has been successfully written to iris_output.csv